name: visual diff
on:
  workflow_run:
    workflows:
      - acceptance
    types:
      - completed
  # Temporary
  pull_request:
    workflows:
      - acceptance
    types:
      - completed

jobs:
  changes:
    runs-on: ubuntu-18.04
    # Set job outputs to values from filter step
    outputs:
      backend_or_frontend: ${{ steps.filter.outputs.backend_or_frontend }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout sentry

      - name: Check for FE or BE file changes
        uses: getsentry/paths-filter@v2
        id: filter
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml

  # This check is to fake that Visual Snapshot run successfully in order to meet
  # the required check
  visual-snapshot:
    needs: changes
    runs-on: ubuntu-18.04
    name: Visual Snapshot
    # This is the opposite to the visual-diff check
    if: needs.changes.outputs.backend_or_frontend != 'true'
    steps:
      - run: 'echo "No Visual Snapshots required." '

  visual-diff:
    needs: changes
    if: needs.changes.outputs.backend_or_frontend != 'true' && github.repository == 'getsentry/sentry'
    runs-on: ubuntu-18.04
    timeout-minutes: 20

    steps:
      - name: Diff snapshots
        id: visual-snapshots-diff
        uses: getsentry/action-visual-snapshot@v2
        with:
          api-token: ${{ secrets.VISUAL_SNAPSHOT_SECRET }}
          gcs-bucket: 'sentry-visual-snapshots'
          gcp-service-account-key: ${{ secrets.SNAPSHOT_GOOGLE_SERVICE_ACCOUNT_KEY }}
