name: visual diff
on:
  workflow_run:
    workflows:
      - acceptance
    types:
      - completed
  # Temporary
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-18.04
    # Set job outputs to values from filter step
    outputs:
      backend_or_frontend: ${{ steps.filter.outputs.backend_or_frontend }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout sentry

      - name: Check for FE or BE file changes
        uses: getsentry/paths-filter@v2
        id: filter
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml

  visual-diff:
    needs: changes
    if: github.repository == 'getsentry/sentry'
    runs-on: ubuntu-18.04
    timeout-minutes: 20

    steps:
      - name: Diff snapshots
        if: needs.changes.outputs.backend_or_frontend == 'true'
        id: visual-snapshots-diff
        uses: getsentry/action-visual-snapshot@v2
        with:
          api-token: ${{ secrets.VISUAL_SNAPSHOT_SECRET }}
          gcs-bucket: 'sentry-visual-snapshots'
          gcp-service-account-key: ${{ secrets.SNAPSHOT_GOOGLE_SERVICE_ACCOUNT_KEY }}

  # Theses checks are to fake out few required checks
  # Refer to acceptance.yml for the real definitions
  # This avoids having to skip every step instead of the whole workflow
  visual-snapshot:
    # This is the opposite to the visual-diff check
    if: needs.changes.outputs.backend_or_frontend != 'true'
    needs: changes
    runs-on: ubuntu-18.04
    name: Visual Snapshot
    steps:
      - run: 'echo "Check not required." '

  frontend:
    # This is the opposite to the visual-diff check
    if: needs.changes.outputs.backend_or_frontend != 'true'
    needs: changes
    runs-on: ubuntu-18.04
    name: frontend tests
    strategy:
      matrix:
        # XXX: When updating this, make sure you also update CI_NODE_TOTAL.
        instance: [0, 1, 2, 3]
    steps:
      - run: 'echo "Check not required." '

  webpack:
    # This is the opposite to the visual-diff check
    if: needs.changes.outputs.backend_or_frontend != 'true'
    needs: changes
    runs-on: ubuntu-18.04
    name: create frontend bundle
    steps:
      - run: 'echo "Check not required." '

  acceptance:
    # This is the opposite to the visual-diff check
    if: needs.changes.outputs.backend_or_frontend != 'true'
    needs: changes
    name: acceptance
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.8.12]
        instance: [0, 1, 2, 3]
    steps:
      - run: 'echo "Check not required." '

  chartcuterie:
    # This is the opposite to the visual-diff check
    if: needs.changes.outputs.backend_or_frontend != 'true'
    needs: changes
    name: chartcuterie integration
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.8.12]
        instance: [0]
    steps:
      - run: 'echo "Check not required." '
